/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedVehiclesRouteImport } from './routes/_authed/vehicles'
import { Route as AuthedTransactionsRouteImport } from './routes/_authed/transactions'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedLoansRouteImport } from './routes/_authed/loans'
import { Route as AuthedCustomersRouteImport } from './routes/_authed/customers'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedVehiclesRoute = AuthedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedTransactionsRoute = AuthedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedLoansRoute = AuthedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCustomersRoute = AuthedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/customers': typeof AuthedCustomersRoute
  '/loans': typeof AuthedLoansRoute
  '/reports': typeof AuthedReportsRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/vehicles': typeof AuthedVehiclesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/customers': typeof AuthedCustomersRoute
  '/loans': typeof AuthedLoansRoute
  '/reports': typeof AuthedReportsRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/vehicles': typeof AuthedVehiclesRoute
  '/': typeof AuthedIndexRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/customers': typeof AuthedCustomersIndexRoute
  '/customers/$customerId/edit': typeof AuthedCustomersCustomerIdEditRoute
  '/customers/$customerId': typeof AuthedCustomersCustomerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/customers': typeof AuthedCustomersRoute
  '/_authed/loans': typeof AuthedLoansRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/transactions': typeof AuthedTransactionsRoute
  '/_authed/vehicles': typeof AuthedVehiclesRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/customers/new': typeof AuthedCustomersNewRoute
  '/_authed/customers/': typeof AuthedCustomersIndexRoute
  '/_authed/customers/$customerId/edit': typeof AuthedCustomersCustomerIdEditRoute
  '/_authed/customers/$customerId/': typeof AuthedCustomersCustomerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customers'
    | '/loans'
    | '/reports'
    | '/transactions'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/customers'
    | '/loans'
    | '/reports'
    | '/transactions'
    | '/vehicles'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/customers'
    | '/_authed/loans'
    | '/_authed/reports'
    | '/_authed/transactions'
    | '/_authed/vehicles'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/vehicles': {
      id: '/_authed/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthedVehiclesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/transactions': {
      id: '/_authed/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedTransactionsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/loans': {
      id: '/_authed/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthedLoansRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/customers': {
      id: '/_authed/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthedCustomersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedCustomersRoute: typeof AuthedCustomersRoute
  AuthedLoansRoute: typeof AuthedLoansRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedTransactionsRoute: typeof AuthedTransactionsRoute
  AuthedVehiclesRoute: typeof AuthedVehiclesRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCustomersNewRoute: typeof AuthedCustomersNewRoute
  AuthedCustomersIndexRoute: typeof AuthedCustomersIndexRoute
  AuthedCustomersCustomerIdEditRoute: typeof AuthedCustomersCustomerIdEditRoute
  AuthedCustomersCustomerIdIndexRoute: typeof AuthedCustomersCustomerIdIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedCustomersRoute: AuthedCustomersRoute,
  AuthedLoansRoute: AuthedLoansRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedTransactionsRoute: AuthedTransactionsRoute,
  AuthedVehiclesRoute: AuthedVehiclesRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCustomersNewRoute: AuthedCustomersNewRoute,
  AuthedCustomersIndexRoute: AuthedCustomersIndexRoute,
  AuthedCustomersCustomerIdEditRoute: AuthedCustomersCustomerIdEditRoute,
  AuthedCustomersCustomerIdIndexRoute: AuthedCustomersCustomerIdIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
