/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedIrrSheetRouteImport } from './routes/_authed/irr-sheet'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedTeamRouteImport } from './routes/_authed/team'
import { Route as AuthedTransactionsRouteImport } from './routes/_authed/transactions'
import { Route as AuthedCustomersIndexRouteImport } from './routes/_authed/customers/index'
import { Route as AuthedCustomersNewRouteImport } from './routes/_authed/customers/new'
import { Route as AuthedFinancesIndexRouteImport } from './routes/_authed/finances/index'
import { Route as AuthedFinancesNewRouteImport } from './routes/_authed/finances/new'
import { Route as AuthedVehiclesIndexRouteImport } from './routes/_authed/vehicles/index'
import { Route as AuthedVehiclesNewRouteImport } from './routes/_authed/vehicles/new'
import { Route as AuthedCustomersCustomerIdIndexRouteImport } from './routes/_authed/customers/$customerId/index'
import { Route as AuthedCustomersCustomerIdEditRouteImport } from './routes/_authed/customers/$customerId/edit'
import { Route as AuthedFinancesLoanIdIndexRouteImport } from './routes/_authed/finances/$loanId/index'
import { Route as AuthedFinancesLoanIdCollectionsRouteImport } from './routes/_authed/finances/$loanId/collections'
import { Route as AuthedFinancesLoanIdEditRouteImport } from './routes/_authed/finances/$loanId/edit'
import { Route as AuthedVehiclesVehicleIdIndexRouteImport } from './routes/_authed/vehicles/$vehicleId/index'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedIrrSheetRoute = AuthedIrrSheetRouteImport.update({
  id: '/irr-sheet',
  path: '/irr-sheet',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedTeamRoute = AuthedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedTransactionsRoute = AuthedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCustomersIndexRoute = AuthedCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCustomersNewRoute = AuthedCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedFinancesIndexRoute = AuthedFinancesIndexRouteImport.update({
  id: '/finances/',
  path: '/finances/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedFinancesNewRoute = AuthedFinancesNewRouteImport.update({
  id: '/finances/new',
  path: '/finances/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedVehiclesIndexRoute = AuthedVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedVehiclesNewRoute = AuthedVehiclesNewRouteImport.update({
  id: '/vehicles/new',
  path: '/vehicles/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCustomersCustomerIdIndexRoute =
  AuthedCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedCustomersCustomerIdEditRoute =
  AuthedCustomersCustomerIdEditRouteImport.update({
    id: '/customers/$customerId/edit',
    path: '/customers/$customerId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFinancesLoanIdIndexRoute =
  AuthedFinancesLoanIdIndexRouteImport.update({
    id: '/finances/$loanId/',
    path: '/finances/$loanId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFinancesLoanIdCollectionsRoute =
  AuthedFinancesLoanIdCollectionsRouteImport.update({
    id: '/finances/$loanId/collections',
    path: '/finances/$loanId/collections',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFinancesLoanIdEditRoute =
  AuthedFinancesLoanIdEditRouteImport.update({
    id: '/finances/$loanId/edit',
    path: '/finances/$loanId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedVehiclesVehicleIdIndexRoute =
  AuthedVehiclesVehicleIdIndexRouteImport.update({
    id: '/vehicles/$vehicleId/',
    path: '/vehicles/$vehicleId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/irr-sheet': typeof AuthedIrrSheetRoute
  '/reports': typeof AuthedReportsRoute
  '/team': typeof AuthedTeamRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/finances/new': typeof AuthedFinancesNewRoute
  '/vehicles/new': typeof AuthedVehiclesNewRoute
  '/customers/': typeof AuthedCustomersIndexRoute
  '/finances/': typeof AuthedFinancesIndexRoute
  '/vehicles/': typeof AuthedVehiclesIndexRoute
  '/customers/$customerId/edit': typeof AuthedCustomersCustomerIdEditRoute
  '/finances/$loanId/collections': typeof AuthedFinancesLoanIdCollectionsRoute
  '/finances/$loanId/edit': typeof AuthedFinancesLoanIdEditRoute
  '/customers/$customerId/': typeof AuthedCustomersCustomerIdIndexRoute
  '/finances/$loanId/': typeof AuthedFinancesLoanIdIndexRoute
  '/vehicles/$vehicleId/': typeof AuthedVehiclesVehicleIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/irr-sheet': typeof AuthedIrrSheetRoute
  '/reports': typeof AuthedReportsRoute
  '/team': typeof AuthedTeamRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/': typeof AuthedIndexRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/finances/new': typeof AuthedFinancesNewRoute
  '/vehicles/new': typeof AuthedVehiclesNewRoute
  '/customers': typeof AuthedCustomersIndexRoute
  '/finances': typeof AuthedFinancesIndexRoute
  '/vehicles': typeof AuthedVehiclesIndexRoute
  '/customers/$customerId/edit': typeof AuthedCustomersCustomerIdEditRoute
  '/finances/$loanId/collections': typeof AuthedFinancesLoanIdCollectionsRoute
  '/finances/$loanId/edit': typeof AuthedFinancesLoanIdEditRoute
  '/customers/$customerId': typeof AuthedCustomersCustomerIdIndexRoute
  '/finances/$loanId': typeof AuthedFinancesLoanIdIndexRoute
  '/vehicles/$vehicleId': typeof AuthedVehiclesVehicleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/irr-sheet': typeof AuthedIrrSheetRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/team': typeof AuthedTeamRoute
  '/_authed/transactions': typeof AuthedTransactionsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/customers/new': typeof AuthedCustomersNewRoute
  '/_authed/finances/new': typeof AuthedFinancesNewRoute
  '/_authed/vehicles/new': typeof AuthedVehiclesNewRoute
  '/_authed/customers/': typeof AuthedCustomersIndexRoute
  '/_authed/finances/': typeof AuthedFinancesIndexRoute
  '/_authed/vehicles/': typeof AuthedVehiclesIndexRoute
  '/_authed/customers/$customerId/edit': typeof AuthedCustomersCustomerIdEditRoute
  '/_authed/finances/$loanId/collections': typeof AuthedFinancesLoanIdCollectionsRoute
  '/_authed/finances/$loanId/edit': typeof AuthedFinancesLoanIdEditRoute
  '/_authed/customers/$customerId/': typeof AuthedCustomersCustomerIdIndexRoute
  '/_authed/finances/$loanId/': typeof AuthedFinancesLoanIdIndexRoute
  '/_authed/vehicles/$vehicleId/': typeof AuthedVehiclesVehicleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/irr-sheet'
    | '/reports'
    | '/team'
    | '/transactions'
    | '/customers/new'
    | '/finances/new'
    | '/vehicles/new'
    | '/customers/'
    | '/finances/'
    | '/vehicles/'
    | '/customers/$customerId/edit'
    | '/finances/$loanId/collections'
    | '/finances/$loanId/edit'
    | '/customers/$customerId/'
    | '/finances/$loanId/'
    | '/vehicles/$vehicleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/irr-sheet'
    | '/reports'
    | '/team'
    | '/transactions'
    | '/'
    | '/customers/new'
    | '/finances/new'
    | '/vehicles/new'
    | '/customers'
    | '/finances'
    | '/vehicles'
    | '/customers/$customerId/edit'
    | '/finances/$loanId/collections'
    | '/finances/$loanId/edit'
    | '/customers/$customerId'
    | '/finances/$loanId'
    | '/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/irr-sheet'
    | '/_authed/reports'
    | '/_authed/team'
    | '/_authed/transactions'
    | '/_authed/'
    | '/_authed/customers/new'
    | '/_authed/finances/new'
    | '/_authed/vehicles/new'
    | '/_authed/customers/'
    | '/_authed/finances/'
    | '/_authed/vehicles/'
    | '/_authed/customers/$customerId/edit'
    | '/_authed/finances/$loanId/collections'
    | '/_authed/finances/$loanId/edit'
    | '/_authed/customers/$customerId/'
    | '/_authed/finances/$loanId/'
    | '/_authed/vehicles/$vehicleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/irr-sheet': {
      id: '/_authed/irr-sheet'
      path: '/irr-sheet'
      fullPath: '/irr-sheet'
      preLoaderRoute: typeof AuthedIrrSheetRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/team': {
      id: '/_authed/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthedTeamRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/transactions': {
      id: '/_authed/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedTransactionsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/customers/': {
      id: '/_authed/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthedCustomersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/customers/new': {
      id: '/_authed/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthedCustomersNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/finances/': {
      id: '/_authed/finances/'
      path: '/finances'
      fullPath: '/finances/'
      preLoaderRoute: typeof AuthedFinancesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/finances/new': {
      id: '/_authed/finances/new'
      path: '/finances/new'
      fullPath: '/finances/new'
      preLoaderRoute: typeof AuthedFinancesNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/vehicles/': {
      id: '/_authed/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AuthedVehiclesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/vehicles/new': {
      id: '/_authed/vehicles/new'
      path: '/vehicles/new'
      fullPath: '/vehicles/new'
      preLoaderRoute: typeof AuthedVehiclesNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/customers/$customerId/': {
      id: '/_authed/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof AuthedCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/customers/$customerId/edit': {
      id: '/_authed/customers/$customerId/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof AuthedCustomersCustomerIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/finances/$loanId/': {
      id: '/_authed/finances/$loanId/'
      path: '/finances/$loanId'
      fullPath: '/finances/$loanId/'
      preLoaderRoute: typeof AuthedFinancesLoanIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/finances/$loanId/collections': {
      id: '/_authed/finances/$loanId/collections'
      path: '/finances/$loanId/collections'
      fullPath: '/finances/$loanId/collections'
      preLoaderRoute: typeof AuthedFinancesLoanIdCollectionsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/finances/$loanId/edit': {
      id: '/_authed/finances/$loanId/edit'
      path: '/finances/$loanId/edit'
      fullPath: '/finances/$loanId/edit'
      preLoaderRoute: typeof AuthedFinancesLoanIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/vehicles/$vehicleId/': {
      id: '/_authed/vehicles/$vehicleId/'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId/'
      preLoaderRoute: typeof AuthedVehiclesVehicleIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedIrrSheetRoute: typeof AuthedIrrSheetRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedTeamRoute: typeof AuthedTeamRoute
  AuthedTransactionsRoute: typeof AuthedTransactionsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCustomersNewRoute: typeof AuthedCustomersNewRoute
  AuthedFinancesNewRoute: typeof AuthedFinancesNewRoute
  AuthedVehiclesNewRoute: typeof AuthedVehiclesNewRoute
  AuthedCustomersIndexRoute: typeof AuthedCustomersIndexRoute
  AuthedFinancesIndexRoute: typeof AuthedFinancesIndexRoute
  AuthedVehiclesIndexRoute: typeof AuthedVehiclesIndexRoute
  AuthedCustomersCustomerIdEditRoute: typeof AuthedCustomersCustomerIdEditRoute
  AuthedFinancesLoanIdCollectionsRoute: typeof AuthedFinancesLoanIdCollectionsRoute
  AuthedFinancesLoanIdEditRoute: typeof AuthedFinancesLoanIdEditRoute
  AuthedCustomersCustomerIdIndexRoute: typeof AuthedCustomersCustomerIdIndexRoute
  AuthedFinancesLoanIdIndexRoute: typeof AuthedFinancesLoanIdIndexRoute
  AuthedVehiclesVehicleIdIndexRoute: typeof AuthedVehiclesVehicleIdIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedIrrSheetRoute: AuthedIrrSheetRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedTeamRoute: AuthedTeamRoute,
  AuthedTransactionsRoute: AuthedTransactionsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCustomersNewRoute: AuthedCustomersNewRoute,
  AuthedFinancesNewRoute: AuthedFinancesNewRoute,
  AuthedVehiclesNewRoute: AuthedVehiclesNewRoute,
  AuthedCustomersIndexRoute: AuthedCustomersIndexRoute,
  AuthedFinancesIndexRoute: AuthedFinancesIndexRoute,
  AuthedVehiclesIndexRoute: AuthedVehiclesIndexRoute,
  AuthedCustomersCustomerIdEditRoute: AuthedCustomersCustomerIdEditRoute,
  AuthedFinancesLoanIdCollectionsRoute: AuthedFinancesLoanIdCollectionsRoute,
  AuthedFinancesLoanIdEditRoute: AuthedFinancesLoanIdEditRoute,
  AuthedCustomersCustomerIdIndexRoute: AuthedCustomersCustomerIdIndexRoute,
  AuthedFinancesLoanIdIndexRoute: AuthedFinancesLoanIdIndexRoute,
  AuthedVehiclesVehicleIdIndexRoute: AuthedVehiclesVehicleIdIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
